// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ssrhvkewfijkyylgffzs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzcmh2a2V3Zmlqa3l5bGdmZnpzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1MDg5NDEsImV4cCI6MjA2MzA4NDk0MX0.Wute4ADWntAjh5usU3fbTzJ13LX1jxH2NeaSsx2sogY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);