// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://epughznptgnfgiobwhhy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVwdWdoem5wdGduZmdpb2J3aGh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0ODk4MjEsImV4cCI6MjA2NDA2NTgyMX0.23gGz1L0pzcg-NgDMmntpVwjhKXo19mSCE4o1w7_0J8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);